### ISSUE TITLE
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable during precise evaluation after training completes

### ISSUE THREAD

**Issue by yxchng** [Pointcept/Pointcept#202]
```
[2024-04-05 03:58:42,726 INFO misc.py line 260 4041230] >>>>>>>>>>>>>>>> Start Precise Evaluation >>>>>>>>>>>>>>>>
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[rank1]:[W CUDAGuardImpl.h:116] Warning: CUDA warning: CUDA-capable device(s) is/are busy or unavailable (function destroyEvent)
[2024-04-05 03:58:42,904 INFO test.py line 41 4041230] => Loading config ...
[2024-04-05 03:58:42,904 INFO test.py line 53 4041230] => Building test dataset & dataloader ...
[2024-04-05 03:58:42,905 INFO s3dis.py line 55 4041230] Totally 68 x 1 samples in Area_5 set.
[2024-04-05 03:58:42,906 INFO misc.py line 271 4041230] => Testing on model_best ...
[2024-04-05 03:58:43,749 INFO test.py line 119 4041230] >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/tools/train.py", line 44, in <module>
    main()
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/tools/train.py", line 33, in main
    launch(
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/pointcept/engines/train.py", line 182, in train
    self.after_train()
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/pointcept/engines/train.py", line 115, in after_train
    h.after_train()
  File "/home/user/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe_debug_2xA100/code/pointcept/engines/hooks/misc.py", line 275, in after_train
    checkpoint = torch.load(best_path)
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/serialization.py", line 1408, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/serialization.py", line 1382, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/serialization.py", line 391, in default_restore_location
    result = fn(storage, location)
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/serialization.py", line 271, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/_utils.py", line 108, in _cuda
    with torch.cuda.device(device):
  File "/home/user/cache/conda/envs/oneformer3d/lib/python3.10/site-packages/torch/cuda/__init__.py", line 374, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
```

This error is quite weird because I am using CUDA during training. But once training ends, and during the precise evaluation phase, it complains about no CUDA device.

**Comment by Gofinge** [comment]
Hi, I currently have not encountered a similar issue that this. I will come back when I have some points about this issue.

**Comment by yxchng** [comment]
Think it is due to out of memory. I resolved this by doing `map_location='cpu' but still weird because I am using 4xA100, each having 80gb, which is the same as your setting).
