### ISSUE TITLE
Loss=nan in the middle of the trainig

### ISSUE THREAD

**Issue by SpeedyGonzales949** [Pointcept/Pointcept#283]
Hi!
I am training PTv3 on a custom dataset using RTX 4070. I am training with a batch size of 2, and my point clouds differ a lot in the number of points, some may contain 10k points and some may contains 150k points.  In the middle of training the loss becomes nan for some training samples. I checked the training samples and they have nothing wrong. After ~100 iterations of loss=nan, the program stops and prints this stack trace. As from other issue #181  I understand I must disable mixed precision. However, are there any other solutions that do not hinder the performance of the model ? Also what exactly is the issue that makes the loss become  Nan?

[2024-06-21 13:25:22,323 INFO misc.py line 118 643976] Train: [1/2][17970/39839] Data 0.004 (0.004) Batch 0.282 (0.333) Remain 05:42:45 loss: nan Lr: 0.00182
NaN or Inf found in input tensor.

[2024-06-21 13:25:22,573 INFO misc.py line 118 643976] Train: [1/2][17971/39839] Data 0.004 (0.004) Batch 0.250 (0.333) Remain 05:42:44 loss: nan Lr: 0.00182
NaN or Inf found in input tensor.

[2024-06-21 13:25:22,828 INFO misc.py line 118 643976] Train: [1/2][17972/39839] Data 0.004 (0.004) Batch 0.255 (0.333) Remain 05:42:43 loss: nan Lr: 0.00182
NaN or Inf found in input tensor.

[2024-06-21 13:25:23,060 INFO misc.py line 118 643976] Train: [1/2][17973/39839] Data 0.004 (0.004) Batch 0.232 (0.333) Remain 05:42:43 loss: 0.6367 Lr: 0.00182

/opt/conda/conda-bld/pytorch_1695392020195/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [39,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1695392020195/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [39,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1695392020195/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [39,0,0], thread: [34,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
.
.
  File "Pointcept/pointcept/engines/train.py", line 188, in run_step
    self.scaler.scale(loss).backward()
  File "anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "anaconda3/envs/pointcept/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by SpeedyGonzales949** [comment]
It turns out that the "seg_logits" are nan. So the input to the loss function is nan. I managed to print the max value of each parameter of each model:
('backbone.dec.dec1.block1.attn.proj.bias', tensor(0.1651, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec1.block1.norm2.0.weight', tensor(1.0296, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec1.block1.norm2.0.bias', tensor(0.0456, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec1.block1.mlp.0.fc1.weight', tensor(0.2146, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec1.block1.mlp.0.fc1.bias', tensor(0.1171, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec1.block1.mlp.0.fc2.weight', tensor(0.1314, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec1.block1.mlp.0.fc2.bias', tensor(0.0982, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj.0.weight', tensor(0.6569, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj.0.bias', tensor(0.2961, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj.1.weight', tensor(1.2581, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj.1.bias', tensor(0.3137, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj_skip.0.weight', tensor(0.6217, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj_skip.0.bias', tensor(0.4010, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj_skip.1.weight', tensor(0.9830, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.up.proj_skip.1.bias', tensor(0.1779, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.cpe.0.weight', tensor(0.1423, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.cpe.0.bias', tensor(0.0375, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.cpe.1.weight', tensor(0.1572, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.cpe.1.bias', tensor(0.1347, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.cpe.2.weight', tensor(0.9731, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.cpe.2.bias', tensor(0.0153, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.norm1.0.weight', tensor(1.0490, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.norm1.0.bias', tensor(0.0439, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.attn.qkv.weight', tensor(0.2175, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.attn.qkv.bias', tensor(1.9606, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.attn.proj.weight', tensor(0.1767, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.attn.proj.bias', tensor(0.1247, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.norm2.0.weight', tensor(1.0328, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.norm2.0.bias', tensor(0.0603, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.mlp.0.fc1.weight', tensor(0.1978, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.mlp.0.fc1.bias', tensor(0.1076, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.mlp.0.fc2.weight', tensor(0.1138, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block0.mlp.0.fc2.bias', tensor(0.0610, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.cpe.0.weight', tensor(0.1364, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.cpe.0.bias', tensor(0.0355, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.cpe.1.weight', tensor(0.1576, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.cpe.1.bias', tensor(0.1362, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.cpe.2.weight', tensor(0.9839, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.cpe.2.bias', tensor(0.0107, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.norm1.0.weight', tensor(1.0723, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.norm1.0.bias', tensor(0.0606, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.attn.qkv.weight', tensor(0.2600, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.attn.qkv.bias', tensor(2.6274, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.attn.proj.weight', tensor(0.1735, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.attn.proj.bias', tensor(0.1208, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.norm2.0.weight', tensor(1.0200, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.norm2.0.bias', tensor(0.0342, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.mlp.0.fc1.weight', tensor(0.2062, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.mlp.0.fc1.bias', tensor(0.1186, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.mlp.0.fc2.weight', tensor(0.1314, device='cuda:0', grad_fn=<MaxBackward1>))
('backbone.dec.dec0.block1.mlp.0.fc2.bias', tensor(0.0593, device='cuda:0', grad_fn=<MaxBackward1>))

**Comment by Gofinge** [comment]
Hi, try to set enable_amp=False or reduce lr.

**Comment by SpeedyGonzales949** [comment]
Yeah, so gradient clipping definitely solved the network instability. The other issue I had, is that some of my point clouds had a lot of noisy points, and after Sphere Crop the pc only contained ignore_class. Therefore having the loss nan.

Thanks for the help!!

**Comment by Gofinge** [comment]
> Yeah, so gradient clipping definitely solved the network instability. The other issue I had, is that some of my point clouds had a lot of noisy points, and after Sphere Crop the pc only contained ignore_class. Therefore having the loss nan.
> 
> This is the line I used : `torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)`
> 
> Thanks for the help!!

Great. If you want, I would appreciate it if you could open a PR with this feature.

**Comment by SpeedyGonzales949** [comment]
Haha, thought about that too. Will do!

**Comment by frapit** [comment]
I am having similar issues, both reasons apply to my data as well. Sometimes the losses get `nan` due to network instability and sometimes because there is only `ignore_class` left (I printed `print(torch.unique(input_dict['segment']))`), so the calculation of the loss fails. How did you fix this @SpeedyGonzales949? Would you mind including your other fixes in the PR as well? The input point cloud seems to contain more classes, so this should probably be handled in the loss or the sample should be skipped somewhere else?
