### ISSUE TITLE
PTv3's docker environment requirement

### ISSUE THREAD

**Issue by hbzhou530** [Pointcept/Pointcept#302]
Thanks for your solid work.
I was trying to reproduce PTv3, but I encountered the same problem on [No. 169 issue](https://github.com/Pointcept/Pointcept/issues/169).
1. My environmental installation steps follow [the official description](https://github.com/Pointcept/PointTransformerV3?tab=readme-ov-file#environment) .
2. The environment is modified from  ```PyTorch/PyTorch: 2.1.0-CUDA11.8-CUDNN8-Devel``` in Docker.
3. Can you provide Docker Image suitable for PTv3 running?
4. The nVidia Driver of **Physical Machines** (check by nvidia-smi) is  "Driver Version: 470.82.01  CUDA Version: 11.4".  Caused by this?  
5. Do the CUDA on the **physical machine** (must it **contain or not** include the driver) need to be upgraded ≥11.8?

THX again!!

``` bash
***/PointTransformerV3/Pointcept/exp/nuscenes/semseg-pt-v3m1-0-base
Loading config in: configs/nuscenes/semseg-pt-v3m1-0-base.py
Running code in: exp/nuscenes/semseg-pt-v3m1-0-base/code
 =========> RUN TASK <=========
Traceback (most recent call last):
  File "exp/nuscenes/semseg-pt-v3m1-0-base/code/tools/train.py", line 38, in <module>
    main()
  File "exp/nuscenes/semseg-pt-v3m1-0-base/code/tools/train.py", line 27, in main
    launch(
  File "/202331510165/code/pvt3/PointTransformerV3/Pointcept/exp/nuscenes/semseg-pt-v3m1-0-base/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/202331510165/code/pvt3/PointTransformerV3/Pointcept/exp/nuscenes/semseg-pt-v3m1-0-base/code/pointcept/engines/launch.py", line 135, in _distributed_worker
    comm.synchronize()
  File "/202331510165/code/pvt3/PointTransformerV3/Pointcept/exp/nuscenes/semseg-pt-v3m1-0-base/code/pointcept/utils/comm.py", line 86, in synchronize
    dist.barrier(device_ids=[torch.cuda.current_device()])
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by hbzhou530** [comment]
Solved by install nvidia-driver-520

**Comment by Gofinge** [comment]
spconv is not updated for CUDA 12.3 (https://github.com/traveller59/spconv)
Downgrade CUDA version or build spconv from scratch.
