### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by joao-alemao** [Pointcept/Pointcept#79]
Hey, I am using pctv2 for training a custom segmentation dataset and, after a few epochs of stable training, I am reaching a point where I get a CUDA illegal memory access error. Was wondering if you would have some intuition as to why this happens?
The error comes from the `pointops.grouping` method call.

Trache
File ".conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/point_transformer_v2m2_base.py", line 559, in forward
    points = self.dec_stages[i](points, skip_points, cluster)
  File "/.conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/point_transformer_v2m2_base.py", line 397, in forward
    return self.blocks(points)
  File ".conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/point_transformer_v2m2_base.py", line 230, in forward
    points = block(points, reference_index)
  File ".conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/point_transformer_v2m2_base.py", line 174, in forward
    self.attn(feat, coord, reference_index)
  File ".conda/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/point_transformer_v2m2_base.py", line 117, in forward
    value = pointops.grouping(reference_index, value, coord.contiguous(), with_xyz=False)
  File ".conda/envs/pointcept/lib/python3.8/site-packages/pointops-1.0-py3.8-linux-x86_64.egg/pointops/grouping.py", line 47, in grouping
    grouped_feat = feat[idx.view(-1).long(), :].view(m, nsample, c)  # (m, num_sample, c)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
 34%|██████████████▏                          | 218/632 [02:57<05:37,  1.22it/s]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    Trainer.train()
  File "train.py", line 76, in train
    scaler.scale(loss).backward()
  File ".conda/envs/pointcept/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File ".conda/envs/pointcept/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by Gofinge** [comment]
Hi, I have not encountered a similar issue. Could you locate the point cloud that led to the error and share the point cloud with me? I need to reproduce this error before finding the reason.

**Comment by ayushjain1144** [comment]
I also see this error especially when using cuda-11.6. This pytorch issue is related I think but doesn't help fix the issue: https://discuss.pytorch.org/t/illegal-memory-access-in-backward-after-first-training-epoch/920/8. Also, this issue is not due to a specific pointcloud as far as I understand.

**Comment by Leon1207** [comment]
Maybe the grouping sample ratio or number too larger for the memory?

**Comment by LSnyd** [comment]
I am running into the same problem. @joao-alemao did you find a solution for this?

**Comment by joao-alemao** [comment]
> I am running into the same problem. @joao-alemao did you find a solution for this?

Sadly no

**Comment by Gofinge** [comment]
This is an extremely rare issue and is usually caused by different reasons. It may caused by local code env, data issues, or some parameter tuning. So my suggestion is to reverse to one version without the issue, then carefully ablate the issue.

If you already know it might be a data issue. Locate the data and print the data shape from each layer of the model.

**Comment by LSnyd** [comment]
I finally found the error in my code!
It seems like pointops works by default with cuda:0, which caused that I had some tensors on this gpu, while others were on the one that I defined. Setting `CUDA_VISIBLE_DEVICES` should help to solve this.

**Comment by Gofinge** [comment]
> I finally found the error in my code! It seems like pointops works by default with cuda:0, which caused that I had some tensors on this gpu, while others were on the one that I defined. Setting `CUDA_VISIBLE_DEVICES` should help to solve this.

Great

**Comment by jdjiang312** [comment]
> I finally found the error in my code! It seems like pointops works by default with cuda:0, which caused that I had some tensors on this gpu, while others were on the one that I defined. Setting `CUDA_VISIBLE_DEVICES` should help to solve this.

Hello, @LSnyd. Sorry to bother you.
I also encountered this problem, but I am a little confused about your answer. I only have one GPU, so I entered export **CUDA_LAUNCH_BLOCKING=1** in the terminal and started training the Swin3D model. However, the error still exists. I would like to ask you how you solved this problem specifically?

**Comment by LSnyd** [comment]
Hi @jdjiang312, I only had GPU 3 for instance available, so I set CUDA_VISIBLE_DEVICES="3" in my terminal beforehand.

**Comment by jdjiang312** [comment]
> Hi @jdjiang312, I only had GPU 3 for instance available, so I set CUDA_VISIBLE_DEVICES="3" in my terminal beforehand.

Thank you so much for your prompt and kind reply, but the problem still exists. I will try some more. Thank you.

**Comment by LiYiquan9** [comment]
I had the same issue, and I fixed it by ensuring all the variables were on the same device.
